<?xml version="1.0" encoding="utf-8"?><Database Name="Calendar" Class="DataClasses1DataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=WIN-BR9AAF20AAG;Initial Catalog=Calendar;Persist Security Info=True;User ID=sa" SettingsObjectName="ConsoleApp1.Properties.Settings" SettingsPropertyName="CalendarConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Users" Member="Users">
    <Type Name="Users">
      <Column Name="Id_User" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Name" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="Role" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Mobile" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
    </Type>
  </Table>
</Database>